name: Publish Release

on:
    push:
        tags:
            - '*'

permissions:
    contents: write

jobs:
    release-free:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies
              run: npm install --force

            - name: Build
              run: npm run build

            - name: Remove all .map files
              run: find . -name "*.map" -type f -delete

            - name: Create ai-image directory and move files
              run: |
                  mkdir -p ai-image &&
                  find . -maxdepth 1 -not -name 'ai-image' -exec mv {} ai-image \;

            - name: Archive release
              uses: thedoctor0/zip-release@0.7.6
              with:
                  filename: 'ai-image.zip'
                  exclusions: '/*.git/* /*.DS_Store/* /*.vscode/*  /*.idea/*  /*.github/* /*.gitignore /*.gitattributes /*.editorconfig /*.prettierrc/*  /*.eslintrc/* /*.babelrc/* /*.distignore/* /*.stylelintrc/* /*node_modules/* /*README.md /*Gruntfile.js /*package.json /*package-lock.json /*composer.lock /*webpack.config.js /*index.js.LICENSE.txt /*README.md /*.phpcs.xml /*postcss.config.js /*tailwind.config.js /*.buildignore /*src/*'
            - name: Display release
              run: ls -a

            - name: Create Release
              uses: ncipollo/release-action@v1.14.0
              with:
                  artifacts: './ai-image.zip'
                  token: ${{ secrets.TOKEN }}
                  removeArtifacts: true
                  allowUpdates: true
                  makeLatest: true
                  tag: ${{ github.ref_name }}
